### ISSUE TITLE
Add Playlist Feature

### ISSUE THREAD

**Issue by johancilliers22** [taoletsgo/custom_races#3]
How could you add a Playlist feature where the user can select multiple races, and be able to race them in a row, with a leaderboard setup for example, so you can play more than 1 race at a time?

**Comment by taoletsgo** [comment]
great suggestion. I'll consider implementing this in a future update

**Comment by musictomy** [comment]
hello I bought races creator from origen (races creator) a while back, so who actually owns this code? as i cam across your code from a video on youtube

**Comment by taoletsgo** [comment]
It seems that players in my server do not use the test version of playlist in beta script, people don't vote at the end of the race, but choose to exit directly to free mode, so I will cancel this dev 🫤
