### ISSUE TITLE
Add fixture removal

### ISSUE THREAD

**Issue by racingpro** [taoletsgo/custom_races#6]
One of the best additions to the vanilla race creator was the ability to remove in-world fixtures, which made making tracks in certain areas (like those in the city) much easier. Adding fixture removal to the script would allow the use of tons more circuits that rely on this feature.

Some documentation on the UGC data, in case this helps:
-`mission.dhprop` contains the relevant data
-`bits` determines what features are used ie 1 is a single removal, whereas 17 is an area removal
-`mn` is the model IDs
-`mnSwap` is, as far as I know, normally unused
-`no` is the number of removals
-`pos` is the location of the fixture/radius
-`wprad` is the radius used for the area removals

I can also provide circuits that I have made (where I thus know what fixtures would be removed) if that would be of any help.

**Comment by taoletsgo** [comment]
thx for your info.

I have previously explored the decryption of this part based on jora creator tool, but I have not updated GTAO since 2023, and I have not found the relevant job json, so I deleted that function before . 

I will add this function to the dev branch again tomorrow, but it has not been tested enough yet.

**Comment by taoletsgo** [comment]
![image](https://github.com/user-attachments/assets/09ccd2b6-9fa5-4811-83f4-bb5083cdebba)

weird, it works for me 🤔

Also note that this loop will only retrieve entities in a specific object pos if the player is nearby, and will return 0 if the entity has been previously deleted.
https://github.com/taoletsgo/custom_races/blob/56bf3f12b7a6366624eb73ab6c6f49fd3e5d5854/main%20script/custom_races/client/main_client.lua#L2263-L2293

You can comment out these codes and add test commands like I did:

```lua
RegisterCommand('removetest', function()
	if #track.dhprop > 0 and (status == "racing" or status == "spectating") then
		local playerCoords = GetEntityCoords(PlayerPedId())
		for i = 1, #track.dhprop do
			local objectCoords = vector3(track.dhprop[i]["x"], track.dhprop[i]["y"], track.dhprop[i]["z"])
			if #(playerCoords - objectCoords) <= 300.0 then
				local object = GetClosestObjectOfType(track.dhprop[i]["x"], track.dhprop[i]["y"], track.dhprop[i]["z"], track.dhprop[i]["radius"], track.dhprop[i]["hash"], false)
				if object > 0 then
					print(track.dhprop[i]["hash"], object)
					SetEntityAsMissionEntity(object, true, true)
					DeleteEntity(object)
				end
			end
		end
	end
end)
```

By the way, `wprad` refers to the radius of the object in GTAO, not the area radius. 
![image](https://github.com/user-attachments/assets/bb58f9fb-e50b-4fea-9baf-a58f84c6af16)
The default value is 3.0, which basically only allows you to select a single object.

if you want to remove all same hash entities in race, you can change the objectCoords in GetClosestObjectOfType to playerCoords and increase the radius to 100, which should be able to remove entities in any area of ​​the map.
But that's not the way json works, so this script can't remove all road/traffic/sign props like your test script does
